### ISSUE TITLE
Mass import of forums

### ISSUE THREAD

**Issue by lecoultre** [ellmetha/django-machina#100]
How does one mass import forums via the console ?

I have tried the following but get error messages:

>>> python manage.py shell
>>>from machina.apps.forum.abstract_models import AbstractForum
>>> from machina.core.db.models import model_factory
>>> Forum = model_factory(AbstractForum)
>>> Rock = Forum.objects.create(name='Rock', type=Forum.FORUM_CAT)
AttributeError: 'NoneType' object has no attribute 'objects'

Alternatively:

>>> Rock = AbstractForum.objects.create(name='Rock', type=AbstractForum.FORUM_CAT)
AttributeError: Manager isn't available; AbstractForum is abstract

**Comment by ellmetha** [comment]
The following example would be a better way of doing what you're trying to do:

```
>>> from machina.apps.forum.models import Forum
>>> Forum.objects.create(name='Rock', type=Forum.FORUM_CAT)
```
