### ISSUE TITLE
Disabled select label displays as a dictionary

### ISSUE THREAD

**Issue by hammygoonan** [ellmetha/django-machina#102]
There seems to be an issue with the `SelectWithDisabled` widget.

It output's the `option` label as a stringified dictionary and the `option` itself doesn't have the `disabled` attribute.

I'd say the issue is with line 28 or 29 in django-machina/machina/forms/widgets.py but that's just a guess.

Screenshots:

![screen shot 2018-01-22 at 1 20 04 pm](https://user-images.githubusercontent.com/476520/35202495-2a60a420-ff77-11e7-9b28-14741af57d17.png)

![screen shot 2018-01-22 at 1 20 12 pm](https://user-images.githubusercontent.com/476520/35202499-2d60996e-ff77-11e7-9fb1-6356853a7aa0.png)

**Comment by ellmetha** [comment]
This is related to the way of rendering widgets since Django 1.11. Fixed in 70c5dbd.

Thanks for reporting this! 😉
