### ISSUE TITLE
Restricting Permissions on A Subforum

### ISSUE THREAD

**Issue by HSchmale16** [ellmetha/django-machina#109]
I have an announcements forum that I want to restrict to only moderators for posting, but I need to have everyone able to see it. Is there any way to deny permissions on a subforum, as I have `MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS` already set up. I would prefer not to add every user to a group just to grant the permissions. I only want admins to be able to post to that forum. Everyone is allowed to post in the other forums though.

Looking in the admin panel I can't see anything about applying permissions on a global basis for a forum for anyone besides anonymous users.

**Comment by ellmetha** [comment]
Hello. This is not possible at the time without using specific user groups. 😉 Of course we could add something similar to the "anonymous user permissions" option targeting the "authenticated users" in future releases. Would you like to work on a PR to address this improvement?

**Comment by HSchmale16** [comment]
Sure. Can you point me in the right direction to get started on this?

**Comment by HSchmale16** [comment]
Never mind I figured out a solution. `MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS` just needs to be set to the bare minimum number of permissions. Then you can widen on each forum or set things globally, like in the admin/forums panel -> forum permissions.

**Comment by ellmetha** [comment]
Glad to hear it! Closing the issue. 😉
