### ISSUE TITLE
Can't save or delete Topic

### ISSUE THREAD

**Issue by synw** [ellmetha/django-machina#11]
In the topics admin ( topic details not list ) it generates a validation error trying to save or delete: the error is from an empty post inline. Posts are inline under the topic in the admin, and there is always an empty one that complains about having no subject and content when trying to save the Topic.

Note: why this inline? Is it really necessary?

**Comment by ellmetha** [comment]
Hi,
The inline form is not necessary. I will remove it as it can prevent users to save topics. That said I managed to properly delete topics. ;)

The following commit should solve this problem: 7685892

**Comment by synw** [comment]
Good! Thanks for your reactivity.
