### ISSUE TITLE
Difficulty adding Machina forum to project using steps in "Getting started" documentation

### ISSUE THREAD

**Issue by L-Ron-GitHubbard** [ellmetha/django-machina#110]
First of all, thanks for developing and sharing Machina. 

I am still a beginner at Django, so stupid mistakes from me are quite likely. That said, I run into an error when I try to add a Machina forum to my existing project using the steps in the documentation under [Getting started](https://django-machina.readthedocs.io/en/stable/getting_started.html)
Specifically, what happens is that when trying to run the server (i.e. python manage.py runserver), I get this error: "ImportError: No module named 'board'"

Am I doing something wrong or is the 'Getting started' not up to date?

p.s. It works/runs OK when I try [example_project](https://django-machina.readthedocs.io/en/stable/example_project.html), but then it is not clear to me how to cleanly integrate that example into my existing django project.

**Comment by ellmetha** [comment]
Could you give more details (eg. complete traceback)? It's really difficult what could be the problem without more details. 😉

**Comment by davidmcdonald** [comment]
I am having the same issue. In my urls.py file i my project I have added the import statement

`from machina.app import board`

From there I have added to my urs.py the following because I am using Django 2.1.1

`path('forum/', include('board.urls')),`

This didn't work so I tried it as per the document using

`url(r'^forum/', include(board.urls)),`

And still will not allow the server to run. Still same error which is...
**"ModuleNotFoundError: No module named 'board'"**

Any help would be greatly appreciated.

**Comment by Craeckie** [comment]
Same problem here, now the documentation says:
```lang=python
from machina import urls as machina_urls

urlpatterns = patterns(
    # [...]
    # Apps
    url(r'^forum/', include(machina_urls)),
)
```
But I'm getting this error:
`ImportError: cannot import name 'urls' from 'machina' (.../env/lib/python3.7/site-packages/machina/__init__.py)`

**Comment by ellmetha** [comment]
@Craeckie please consult the `stable` version of the documentation: https://django-machina.readthedocs.io/en/stable/getting_started.html#urls-configuration

The `latest` version relates to the development version of the module (which is not yet released). 😉

**Comment by Craeckie** [comment]
Thanks for the quick response!

This issues coms up after updating Django 1.11 -> 2.1.1.

Now I'm getting the following error:
`ImproperlyConfigured: "^schlange/(?P1\d+)/ablehnen$" is not a valid regular expression: unknown extension ?P1 at position 11`
This seems to come from [forum_moderation/urls.py#L88](https://github.com/ellmetha/django-machina/blob/e36edb8c8888dea147d156713920f82b1596f9fa/machina/apps/forum_moderation/urls.py#L88), which in turn is translated to [LC_MESSAGES/django.po#L731](https://github.com/ellmetha/django-machina/blob/2eb8126a80e6a3419503ec6c9445c12a2c4301e6/machina/locale/de/LC_MESSAGES/django.po#L731).

Here the `<pk>` appears to be lost. Is that on purpose?

**Comment by ellmetha** [comment]
@Craeckie are you using the latest release of django-machina (0.7.1)?

**Comment by Cybernetic1** [comment]
The instructions seems to be incomplete.  After doing all the steps, there is no "machina" directory created in the user's base directory, no "settings.py", "urls.py", etc.
