### ISSUE TITLE
Trouble Overriding Forum model

### ISSUE THREAD

**Issue by hammygoonan** [ellmetha/django-machina#112]
I've been working away trying to override the Form model so that I can implement forum.

I've followed all the instructions of overriding an app. When I run migrations the forum is picked up and a migration is made.

However when I try to use the `Forum` model elsewhere, `Forum` is `None`. So when I trying and get the first forum (`Forum.objects.first()`), I get an error saying `'NoneType' object has no attribute 'objects'` I've tried importing it from `machina.apps.forum.models` and the app I use to override the model but nothing seems to work.

When I print `dir(machina.apps.forum.models)`, `Forum` is in there but it has a value of `None`.

Any ideas what i might be doing wrong?

**Comment by ellmetha** [comment]
How are you importing this overridden model? You should import it from your own `models.py` module. Could you copy paste some of the relevant modules (models, settings, ...)?

**Comment by hammygoonan** [comment]
Thanks for getting back to me @ellmetha .

I got it working, it looks like I wasn't importing it properly. I'm sure I tried importing it from my own `models.py` but obviously not.

Thanks for the great project too!
