### ISSUE TITLE
Show users first and last name instead of username

### ISSUE THREAD

**Issue by Brontes** [ellmetha/django-machina#115]
Hi.

I would like that instead of username there would be first and last name shown across the forum.

I can do this by myself and commit a pull request if this is acceptable for you.

I'm thinking about making new setting FORUM_SHOW_REAL_USER_NAME (default value would be False), and new function that will be called from templates. This function will return users first and last name if FORUM_SHOW_REAL_USER_NAME will be set to True, and users username if setting will be set to False (default).

Regards

**Comment by ellmetha** [comment]
Hi 😉 I agree with the idea to add a new setting to customize the way the "user name" is displayed across forums. That said `FORUM_SHOW_REAL_USER_NAME` seems a bit too specific. Instead, we could ensure that the "display name" of users is retrieved from a specific function or a method defined on the `User` model.

For example:

```
MACHINA_FORUM_USER_DISPLAY_NAME_METHOD = "get_full_name"
```

The name defined in this setting could be used to dynamically retrieve the "display name" of the user each time it is necessary to display it.

What do you think?

**Comment by ellmetha** [comment]
Closing this this was resolved in 8d053ed. Thanks!

**Comment by velis74** [comment]
Just a comment form a user: I'm currently keeping a separate repository for Brontes' solution and was thinking of "reverting" back to your solution.
However, I'm not convinced your solution is that great: it requires me to override your application anyway instead of declaring a setting in settings.py. I will constantly have to worry about that app override and whether it's still compatible, each time I do a pip install -U.

**Comment by ellmetha** [comment]
@velis74 I understand your point but in this case overriding the application only means that you create a package with references to the original application in your project. Even in the app evolves with new releases it will remain compatible - it's not like if you were overriding every part of the app with custom code or logic.

The thing is I don't want to add a setting based on a custom importation logic while all the customization abilities of the module already relies on a dynamic importation mechanism. It's just not gonna to happen. _That being said_, I could see the benefit of a setting that'd ease the customization of the user display name by defining which User model method should be used by django-machina - eg. should it be the standard [get_username](https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.get_username) or [get_short_name](https://docs.djangoproject.com/en/2.1/ref/contrib/auth/#django.contrib.auth.models.User.get_short_name) or another custom method defined on the User model (which is likely to be overridden on the Django project, right?)?

It could be something like `MACHINA_FORUM_USER_DISPLAY_NAME_METHOD` (as I already mentioned in this issue):

```python
MACHINA_FORUM_USER_DISPLAY_NAME_METHOD = "get_full_name"
```
