### ISSUE TITLE
Avatar showing problems

### ISSUE THREAD

**Issue by Brontes** [ellmetha/django-machina#116]
Hi.

I'm having problems with avatar showing. When I set avatar to user it is saved to media/machina/avatar_images which I believe is correct.

But then on conversation page program is trying to load avatar from 
_[05/Apr/2018 09:07:00] "GET /forum/forum/debata-3/topic/pranje-cessne-521/machina/avatar_images/test_2.png HTTP/1.1" 404 14903_
where _/forum/forum/debata-3/topic/pranje-cessne-521/_ is url to current topic.

Is there something wrong on my side or is this forum issue?

Regards.

**Comment by ellmetha** [comment]
I'd say that there is something wrong in your media configuration. 😉 Could you double-check it?

**Comment by Brontes** [comment]
You are right.
There was no `MEDIA_URL` setting in my settings.py.

I also have to add `static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)` to `urlpatterns` in urls.py.

Thanks.
