### ISSUE TITLE
Missing translation in template

### ISSUE THREAD

**Issue by synw** [ellmetha/django-machina#12]
In the template `forum/forum_detail.html` a text string is within a templatetag and is not translated: [see here](https://github.com/ellmetha/django-machina/blob/master/machina/templates/machina/forum/forum_detail.html#L46)

**Comment by ellmetha** [comment]
Hi!
Thanks for reporting this! Could you provide a pull request to address this problem? :)

**Comment by synw** [comment]
I can't make it work. I don't know what happens here. I tried things like:

`{% trans "Announcements" as topic_list_title %}`

I have noticed that the problem only occurs with the word "Announcements". If I replace it with another word the translation works.

**Comment by ellmetha** [comment]
This seems to be the correct way to do it. ;)

**Comment by ellmetha** [comment]
@synw do you plan to provide a pull request to address this issue
