### ISSUE TITLE
Impossible actions available in admin

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#120]
In the admin interface you are always presented with a 'add subforum' button, but for example below a link-forum it is not allowed to make a subforum. However, you are only told that when you try to save your subforum.

Also, creating a category below a category is not allowed, but the option is there in the pulldown.

I think it would be better if these options are not available if they can not be used.

**Comment by ellmetha** [comment]
Thanks for reporting this! Would you like submitting a PR for this improvement? 😉

**Comment by ellmetha** [comment]
Closing for now. @BrendaH please re-open an issue if you'd like to work on the sub-category behaviour.
