### ISSUE TITLE
Deleting users issue

### ISSUE THREAD

**Issue by vaughn-baby2body** [ellmetha/django-machina#123]
For GDPR the users have the right to be forgotten, so when deleting a user that has forum posts:
CODE:
u = User.objects.get(id = user_id)
u.delete()

ERROR:
new row for relation "forum_member_forumprofile" violates check constraint "forum_member_forumprofile_posts_count_check"
DETAIL:  Failing row contains (15, , null, -1, null, 594817).

EDIT:
I have also tried deleting the Topic and Forum profile beforehand.

CODE:
from machina.apps.forum_conversation.models import Topic
t = Topic.objects.filter(poster_id=user_id)
t.delete()

from machina.apps.forum_member.models import ForumProfile
f =  ForumProfile.objects.get(user_id=user_id)
f.delete()

**Comment by ellmetha** [comment]
You just need to delete the `ForumTopic`, `ForumPost` and `ForumProfile` instances related to the considered user (and then delete the considered user). That said deleting the user "directly" works too (I've just tested it). 😉
