### ISSUE TITLE
Editing user/group permissions permitted despite settings of rights

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#126]
In the Django admin you have a 'auth' department, giving an interface to manage users, groups and rights. But regardless of giving or denying a group or user rights to edit the forum permissions (for a group or a user); I still get the user/group interface when editing forum rights.

I'm trying to make a pull request to fix this, but I came upon the usage of the ForeignKeyRawIdWidget of Django itself, which shows a looking glass to search for users/groups, but does not take into account the right to actually see the list of users/groups (which, in Django, is represented by the right to change user/group). Resulting in a popup with a 403 Forbidden error if the right to auth.change_[user|group] is not granted. Making the whole interface quite useless.

Since I want to keep the right to edit forum permissions for groups/users separate from being allowed to change the users/groups themselves, I was wondering why the ForeignKeyRawIdWidget is used, and why not the standard select (perhaps with filtering for long lists) for which you won't need the auth.change_[user|group] permission?
Is this something that may be changed? Can we use the default select widget instead?

**Comment by ellmetha** [comment]
👍 for starting fixing this behaviour.

> Is this something that may be changed? Can we use the default select widget instead?

Not be a good idea. This widget is used because selecting users using a select-box interface (`<select>`) would incur an overhead if your user base is big enough (eg. more than 500 users).

**Comment by BrendaH** [comment]
What do you mean by 'incur an overhead'? That it would take too much computing power, or that it would be too difficult for the user to navigate?

How about using the default (select) interface if there's no auth.change_[user|group] right, and otherwise the ForeingKeyRawIdWidget?
Or perhaps make it an option. I have a custom field for users to display their whole name and username (instead of only username, which might be quite cryptic) and would like to use that, but not hardcode it into my machina code. Default would be the ForeingKeyRawIdWidget (perhaps with a comment to warn that change right is needed to use the widget)

The main question for me is: how to give forum-admins access to an interface to select user/group without also having to give them access to changing the users/groups themselves.

**Comment by ellmetha** [comment]
Closing. 660b34a introduces a change that allows to rely on the class loading mechanism to easily override forum permission forms (including fields and widgets).

**Comment by BrendaH** [comment]
For those interested, since Django 2.1 it has a view permission on all models and this is enough to use the forum permission interface of selecting a group or user. No more need to give people the change permission on auth.group or auth.user if you only want to let them change forum permissions.
