### ISSUE TITLE
Textual/translation change in template for 'messages'

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#127]
In board_base.html there's the sentence "view my messages" which leads to the page where the user can see his/her own _posts_. But I think "messages" implies something more in the lines of personal messages (PM's like in PHPBB forums) which are not (yet?) implemented in Django-Machina. The same with the Dutch translation "bekijk mijn berichten".
To make it more clear to the users of my project I could overwrite the Dutch translation, but I was wondering if users of the English language agree with the possible confusion? In that case the string needs to be changed.

The button to add a post is called 'post reply' ('plaats reactie' in Dutch) so perhaps the above mentioned link should read 'view my replies' or 'view my posts' with the Dutch translation 'bekijk mijn reacties'.

Any thoughts? More people with this concern?

**Comment by ellmetha** [comment]
IMO "View my posts" would be more appropriate.
