### ISSUE TITLE
Uploaded Avatar 404's

### ISSUE THREAD

**Issue by itsTykho** [ellmetha/django-machina#128]
Using default avatars with machina, when uploading them they lead to a 404:

The requested URL /media/machina/avatar_images/22046944_10104659338360595_893948518511677761_n_oVtbnjO.png was not found on this server.

My media settings are:
```

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
```

**Comment by BrendaH** [comment]
Some things to check:
Is the directory media/machina/avatar_images present?
Are there any (server) errors perhaps stating that the directory can not be created or is not writable?
Is the upload going to the same place as the request for the displaying of the image?

Note: these are the first questions to come to my mind, without looking at any code or configuration. I am using custom avatars myself, so I have not worked with this code and have not encountered this problem.
