### ISSUE TITLE
Permission interface is 'overwhelming'

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#132]
The changelist for group rights or user rights can be quite long, (url like: http://127.0.0.1:8000/nl/admin/forum_permission/groupforumpermission/

I'd like to have a filter option on both forum and group/user. This is easily accomplished by the list_filter setting in the admin class, but should I add this in a PR, or should I overwrite the app and admin.py file in my own project for just changing this setting?

**Comment by ellmetha** [comment]
You can propose a PR. 😉
