### ISSUE TITLE
Namespace error while assigning url 'forum' to an existing project.

### ISSUE THREAD

**Issue by talktomadhur** [ellmetha/django-machina#136]
Hi,
In template file this is how i am linking 'forum' url, objective is to redirect user from current page to machina forum.

`<a href="{% url 'forum' %}">Discussion Forum</a>`

url.py 
```
from machina.app import board
urlpatterns = [
    url(r'^forum/' , include(board.urls),name='forum'),
   ....]
```

But it throws below error

```
NoReverseMatch at /userProfile/
Reverse for 'forum' not found. 'forum' is not a valid view function or pattern name. 
```
Am i doing it correct, or is there some other way?

P.S: It works perfectly fine if i browse `128.0.0.1/forum/`

Madhur

**Comment by ellmetha** [comment]
Please include the URLs like as described in the documentation:

```
from machina.app import board

urlpatterns = patterns(
    # [...]
    # Apps
    url(r'^forum/', include(board.urls)),
)
```

Then if you want to add a link toward the forum index, all you have to do is to use the `forum:index` URL name. 😉

**Comment by talktomadhur** [comment]
That works very well thanks, how about adding same to the document?
