### ISSUE TITLE
Forum permission admin interface doesn't let you edit user/anon user permissions

### ISSUE THREAD

**Issue by rozenmd** [ellmetha/django-machina#144]
Just wanted to say I'm super grateful this project exists - but I'm having an issue trying to set either global or forum-specific permissions for the anonymous user.

Issue occurs for both `<SITE_URL>/admin/forum/forum/1/edit-permissions/` and `<SITE_URL>/admin/forum/forum/edit-global-permissions/`

Version: `django-machina==0.7.1`

Steps to recreate: 
1. Visit the Django Admin form - "Machina: Forum" in `/admin`
1. Click on `Global forum permissions`
1. Tick the checkbox next to `Anonymous`
1. Click `Select`
1. Error appears: `Choose either a user ID, a group ID or the anonymous user`

I've traced it down through `/machina/apps/forum/admin.py` and noticed the request doesn't actually receive the user form data - just the group form data.

Edit:
Actually, funnily enough it lets me just visit the URL: `admin/forum/forum/edit-global-permissions/user/anonymous/` but clicking through the form doesn't work

**Comment by ellmetha** [comment]
I guess that this appear because you're clicking on the "Select" associated with the group selection form instead of the one for the user selection. 😉

**Comment by rozenmd** [comment]
@ellmetha It's the only "Select" on the page:
![image](https://user-images.githubusercontent.com/3822106/47763669-c0976880-dd15-11e8-943f-cae800be4e8a.png)

**Comment by ellmetha** [comment]
Weird. Are you using a special theme for the admin panel?
