### ISSUE TITLE
PDF attachment becomes an <img> ... how and why?

### ISSUE THREAD

**Issue by SundialServices** [ellmetha/django-machina#151]
A user attached a PDF file to a post, only to find that Machina converted it to an **<img>** consisting of page-one of the PDF!

Plus – there is no hyperlink giving access to the original PDF.

In other forum systems, I expect PDFs to appear as an embed which allows the PDF to be read.  (Or, at the very least, to provide a hyperlink corresponding to a "thumbnail.")

Where did this obviously-deliberate behavior come from, and how might I change it?

**Comment by ellmetha** [comment]
Are you referring to machina's attachments? If so, then no. There is no such behavior in django-machina. Unless you can provide a detailed description on how to repreduce the problem, I'm gonna close this issue. 😉

**Comment by SundialServices** [comment]
***EXPLAINED – BUT NOT YET SOLVED:***

Here's some more info:

`forum_attachments_attachment` contains one entry with a name `machina/attachments/GGA_Product_Instructions.pdf` with a comment `PDF`, attached to post-id #222.

`forum_conversation_post` for entry #222 contains `content` consisting only of the introductory paragraph.  `content_rendered` is the same.

I grabbed the file from the web server and ... guess what ... it's a PDF.  The right PDF.

And, well, here's where the "distorted image" is coming from – the uploaded file attached to the post (as seen on TeeVee ...) is also "a PDF."  But it's being referenced by an `<IMG>` tag.  Therefore, _the web browser_ is producing the strange image!  (It's processing a PDF as the input to an `<IMG>` and the browser is doing its best to display it "as an image."

- - - 

So – that's a sufficient technical explanation of why I'm seeing what I'm seeing.

Now, I guess the _real_ question is ... how do I control the HTML-tag treatment that is used for a particular kind of attachment?  (Or, specify that it should not be rendered at all as-such, if need be?)

Notice also that neither the HTML specified in the `content` nor the `content_rendered` fields of the database record ever appeared in the HTML output presented to the user.

**Comment by SundialServices** [comment]
Okay, Elimetha ... I now have a technical explanation of what actually happened here.

The user attached a PDF file to a forum post _using the "attach image" button in the toolbar_, instead of using the "Attachments" tab.

This caused Machine to produce an `<IMG>` tag referencing the `.PDF` file ... and the "dutiful browser obligingly did its best."

So – this now becomes a "feature" request, or a "what can I do about this" request.  Either a PDF-file should have been rejected as an "image" attachment, or _(much preferred ...)_ I need to be able to produce a more-reasonable HTML-handling of this "image" type when we render the post for the user.

No, "Machina didn't do it, after all," but it's a very common thing to do and I/we need to handle it much more gracefully.  (Fine if it turns into a "pull request.")

**Comment by ellmetha** [comment]
By default django-machina ships with a Markdown editor, I guess that you're using CKEditor. So it seems to be a CKEditor issue indeed.
