### ISSUE TITLE
It's possible to reply a locked topic

### ISSUE THREAD

**Issue by tapia** [ellmetha/django-machina#155]
If a topic is marked as locked, the "post reply" button is hidden. That's correct. But if you access the reply form via URL (just by adding `/post/create/` to the end of the topic URL), then you can freely reply to the topic.

Reading the code, the problem seems to be that the `PostCreateView` just checks the `can_reply_to_topics` permission, but it doesn't check anywhere if the topic is locked.

But weirdly, if you try to edit an existing post via url, it correctly returns a `403 forbidden` error.

**Comment by ellmetha** [comment]
👋 

Thanks a lot for reporting this issue! Fixed in 4bc73d8.
