### ISSUE TITLE
Missing migration in 1.0?

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#160]
I have just upgraded to Machina 1.0.1 and executed the 'migrate' command. But when I run a makemigrations command (expecting only migration files for my own code) there's a new migration created for Machina with the following content:

```
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20181103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
```

Should this have been a part of the 1.0 version?

**Comment by ellmetha** [comment]
I guess something must have changed in django-mptt, something triggering the generation of this new migration. I've added the new migration and will release a new minor version of the module soon. Thanks! 😉
