### ISSUE TITLE
Urls broken by missing translations in Dutch (nl-NL)

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#161]
When upgrading from Machina 0.7.1 to 1.0.1 all internal links within my forum were broken because the copy-pasted urls in the posts referred to `.../onderwerp/....` urls. These links now lead to a 404 warning.
When changing the Dutch 'onderwerp' to the English 'topic' in the address bar the url works as it should.

It seems that a lot of these url patterns are missing their translation. Example:
https://github.com/ellmetha/django-machina/blob/a988ad61d32091faf8f1eac613ce34970072b24c/machina/locale/nl_NL/LC_MESSAGES/django.po#L542
Or they have been marked as fuzzy, meaning the translation won't be used.

There was nothing in the release notes about abandoning the translation of url paths, so my guess is that this was an oversight in at least the Dutch translation. (perhaps other languages as well).
This is quite a big problem for me since I have a forum with lots of cross referencing in posts.
I can search/replace all 'onderwerpen' to 'topics' in my database, but won't that break the other way when eventually the translations are fixed again?

**Comment by BrendaH** [comment]
Might it be a better idea to have a setting that defines in which language the urls should be created / stored / retrieved at all times? Independent of the machine/browser/website-setting of the user? That way everybody gets the same urls, independent of who made them with which language settings.

**Comment by ellmetha** [comment]
Translations are managed on Transifex! You can submit changes there if you want. I've just updated the project with the latest version of the translations ; let me know you can make them work using master 😉

**Comment by BrendaH** [comment]
The .mo file was not generated and when I tried to compile the new .po file I got the following error:
```

processing file django.po in C:\[.....]\site-packages\machina\locale\ja_JP\LC_MESSAGES
Execution of msgfmt failed: C:\[.....]\site-packages\machina\locale\nl_NL\LC_MESSAGES\django.po:1759: 'msgid' and 'msgid_plural' entries do not both begin with '\n'
msgfmt: found 2 fatal errors
CommandError: compilemessages generated one or more errors.
```

So, at this moment I can not get it to work.

However, the underlying question is still: should urls be translated?

**Comment by ellmetha** [comment]
They should be _translatable_. And this is already the case.

**Comment by BrendaH** [comment]
Ok, they are marked as 'to be translated' by using a gettext` _()` notation. I get that. But if translations are missing it stops working for that language. Did I miss the setting that tells Machina _if_ urls should be translated? I'd like to turn it off to prevent different people with different OS/browser/whatever settings to create both Dutch and English urls.

**Comment by ellmetha** [comment]
> Did I miss the setting that tells Machina if urls should be translated?

There is no such setting but you're free to contribute one if you want. I don't have a strong opinion on this and I can't think of any projects where the fact that URLs are translatable or not is a configuration option. Perhaps the most appropriate solution would be to not translate URLs at all in that case (this would require a new major release since this could be a breaking change for many projects).

**Comment by ellmetha** [comment]
I've decided to remove the ability for machina's URLs to be translated. The next release (1.1) will include non-translatable URLs. 😉
