### ISSUE TITLE
Unexpected view results group/user rights on forum

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#163]
Perhaps I am misunderstanding the permission system (I've dived into it but do not completely follow the code... I'm afraid).

Example situation:
```
Category forum A
-- Subforum a

User is member of Group

```
Things I checked (read each table row from left to right) :
```
	|	Global	| 	Forum	|	Result	|
=========================================================
Group	|	Yes	|	No	|	No	|
Group	|	No	|	Yes	|	Yes	|
User	|	Yes	|	No	|	No	|
User	|	No	|	Yes	|	Yes	|


	|	Group	| 	User	|	Result	| 	Expected|
=========================================================================
Global	|	Yes	|	No	|	Yes	|	No	|
Global	|	No	|	Yes	|	Yes	|		|
Forum	|	Yes	|	No	|	No	|		|
Forum	|	No	|	Yes	|	No	|	Yes	|

```
Forum seems to take precedence over global, which is what I'd expect.
However, with group/user there seem to be 2 cases that give the opposite result than I'd expect.

I'd expect that, because a user-set permission is more fine-grained than a group-set permission, the user-set permission should take precedence. Regardless of which one says YES and which one says NO.

**Is this intentionally not the case, and if so why?**

(I am trying to implement an target-all-authenticated-users permission, but I first need to understand the current way stuff works.)

**Comment by ellmetha** [comment]
Fixed by #168. Thanks again!
