### ISSUE TITLE
Critical failure while approving posts by anonimous user

### ISSUE THREAD

**Issue by savelmtr** [ellmetha/django-machina#174]
Good afternoon. I've faced with very interesting problem: when admin try to approve a post by anonimous user, django-machina falls in exception. Here is the code of it: [you can check it on pastebin](https://pastebin.com/u6drW9rD).
I definetely don't know what to do with this problem. May be the app tries to get from the database info about user (but user is anonimous and all crashes)? 
Please help me with it!

**Comment by savelmtr** [comment]
Thank you, BrendaH!

**Comment by ellmetha** [comment]
Fixed by #176. Thanks @BrendaH!
