### ISSUE TITLE
Missing indexes on many models

### ISSUE THREAD

**Issue by d9pouces** [ellmetha/django-machina#191]
Most of model fields are not indexed, like the "created" and "updated" fields. 
On a small database (130k posts, 5k topics), this quickly leads to big performance problems.

For example, the request for retrieving the 10 most recent posts drops from 2 seconds to 1,5 milliseconds, just by adding db_index=True (more than 1,000x faster!).

**Comment by BoPeng** [comment]
@ellmetha Could you comment on this? We are searching for a forum app for our website and `django-machina` looks very promissing until I notice that this seemingly serious performance problem.

**Comment by ellmetha** [comment]
I can comment. This should be easily fixable (adding indexes and generating the associated migrations). I will add those in the next few days, with an associated minor release.

**Comment by BoPeng** [comment]
Thanks @ellmetha . I noticed that you just closed https://github.com/ellmetha/django-machina/pull/187. Could you let me know if the search features are working well (may be difficult to configure but works and can scale), or need a lot of work?

**Comment by ellmetha** [comment]
@BoPeng search features rely on [Django-Haystack](https://github.com/django-haystack/django-haystack), so they should work properly depending on the search backend you want to use. Django-Haystack is still supported but not really actively maintained, so if you want support for the latest Elasticsearch version (for example) you might be out of luck.

Revisiting the search implementation for django-machina is something that I plan do at one point but I don't have the time to work on such major evolution right now.

Hope this answers your questions. 😉

**Comment by ellmetha** [comment]
Fixed by a628c8c6767d1d14c3567dcd9fb14e14a9edc490.
