### ISSUE TITLE
Bug: permission on all authenticated users does not work without group permission

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#193]
Found a bug in some of the code I added to Machina.
Apparently when a logged in user does not have a group with rights on forum X, the all_authenticated_users permissions for forum X are not taken into account.
This is a problem with too deep nesting (inside the group_permissions if) of a block of code so it is easily fixed. Will also write a test for it that could have revealed this bug and put it in the same PR.

**Comment by SundialServices** [comment]
Brenda, I wound up just rewriting both the checker and the handler from scratch and now it works beautifully.  The approach that I took is that the code walks through various possibilities from "per-user per-forum" all the way out to "all-users all-forums" ... walking up the forum hierarchy in each step ... creating a list of permissions (granted or denied) but keeping only the first rule that it finds.  This completely eliminated a lot of strange logic in both files.

**Comment by BrendaH** [comment]
Will you put this in a PR for Machina itself, or do you keep this for your project only? I found both handler and checker a bit weird and bloated, but did not clearly see how to fix it (and was busy with my main work at the time).

**Comment by jeffmarshall** [comment]
I can't get the authenticated users per-forum permissions to be respected either. I guess this pull request should address it? I wonder if it will be accepted? Should I switch to one of your branches?
