### ISSUE TITLE
Haystack error with Django 3.0.4

### ISSUE THREAD

**Issue by smokfyz** [ellmetha/django-machina#197]
After `python manage.py migrate` error:

> Traceback (most recent call last):
>   File "manage.py", line 21, in <module>
>     main()
>   File "manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
>     utility.execute()
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
>     django.setup()
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
>     module = import_module(entry)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/haystack/__init__.py", line 11, in <module>
>     from haystack.utils import loading
>   File "/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/haystack/utils/__init__.py", line 9, in <module>
>     from django.utils import six
> ImportError: cannot import name 'six' from 'django.utils' (/home/ivan/Projects/nonut/venv/lib/python3.7/site-packages/django/utils/__init__.py)

**Comment by madmatah** [comment]
Which djange-haystack version do you use ?
With Django 3.x, you have to use django-haystack==3.0b1.
Since this is a pre-release, you have to force this version in your requirements.

**Comment by smokfyz** [comment]
@madmatah Okay, thank you
