### ISSUE TITLE
Where is the functionality to send mail to subscribers?

### ISSUE THREAD

**Issue by SundialServices** [ellmetha/django-machina#198]
The source-code that I'm looking at from pip3 does not even contain a call to "send_mail()."

**Comment by ellmetha** [comment]
👋 It does not indeed. Email notifications (for users who subscribe to topics) is intentionally a feature that is not provided by machina. That being it shouldn't be too complicated to implement it directly in your project if you need it: for example you could define a signal receiver that sends an email when new posts are added to topics. 😉

**Comment by savelmtr** [comment]
> you could define a signal receiver that sends an email when new posts are added to topics.

@ellmetha, I couldn't find the signal that machina sends when new post are added. In the file signals.py is only one signal - it is sended when topic is viewed. So where should I search?

**Comment by ellmetha** [comment]
You have to use a built-in Django signal to do this. For example your signal receiver could look like:

```python
from django.db.models.signals import post_save
from django.dispatch import receiver

from machina.apps.forum_conversation.models import Post

@receiver(post_save, sender=Post)
def notify_subscribers(sender, instance, **kwargs):
    # Do things...
```

**Comment by savelmtr** [comment]
Oh, thanks! Got it)

**Comment by savelmtr** [comment]
Ok, I think i need to append this info. I made a email-sender to my forum and it costed me a day.
So, @SundialServices, below the code of my handlers.py. As @ellmetha can see it has nothing common with simlplicity and shortage. Also I've rewrite an app of the machina 'forum-member' and added two field to it's model - with them users can cancel this mailing.

As a conclusion: @ellmetha, I wouldn't be so sure the mailing function is not need to be included in machina... May be we should add it one day?

```
from django.dispatch import receiver
from django.db.models.signals import post_save
from machina.core.db.models import get_model
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.sites.models import Site
from django.template.defaultfilters import truncatechars_html
from django.urls import reverse
import time
from threading import Thread

Post = get_model('forum_conversation', 'Post')
Topic = get_model('forum_conversation', 'Topic')
ForumProfile = get_model('forum_member', 'ForumProfile')
TopicReadTrack = get_model('forum_tracking', 'TopicReadTrack')
ForumReadTrack = get_model('forum_tracking', 'ForumReadTrack')
User = get_user_model()


@receiver(post_save, sender=Post)
def send_mail_to_users(sender, instance, created, **kwargs):
    if created:
        t = Thread(target=sending_thread, args=(sender, instance, created))
        t.start()

def sending_thread(sender, instance, created):
    time.sleep(3600)
    # Список участников топика
    posters_of_topic = set(Post.objects.filter(topic=instance.topic).values_list('poster', flat=True))
    
    # Список подписчиков топика
    subscribers_of_topic = set(instance.topic.subscribers.values_list('pk', flat=True))

    already_sent = []

    for cycle in ('allow_mail_if_participant', posters_of_topic), ('allow_mail_if_subscribed', subscribers_of_topic):
        #Проверить согласие получателя получать письмо!!!!!
        for recipient in cycle[1]:
            if recipient in already_sent or not getattr(ForumProfile.objects.get(user__pk=recipient), cycle[0]):
                continue
            else:
                already_sent.append(recipient)

                #Проверяем наличие емейла и прочитан ли топик
                user = User.objects.get(pk=recipient)
                if user.email and is_unread(user, instance.topic):
                    message = """
Появился ответ от {0} в теме, на которую вы подписаны.

************
{1}
************
Посмотреть сообщение полностью можно по ссылке: https://{2}{4}?post={5}#{5}

Отказаться от подобных уведомлений можно в настройках профиля: https://{2}/member/profile/{3}/.
                    """.format(
                        instance.poster, 
                        truncatechars_html(instance.content, 200), 
                        Site.objects.get_current(), 
                        user.pk,
                        reverse('forum_conversation:topic', args=[
                            instance.topic.forum.slug, 
                            instance.topic.forum.pk, 
                            instance.topic.slug, 
                            instance.topic.pk
                        ]),
                        instance.pk
                    )
                    send_mail(
                        'Ответ в теме: {}'.format(instance.topic.subject), 
                        message, 
                        settings.DEFAULT_FROM_EMAIL, 
                        [user.email],
                        html_message=None)


def is_unread(user, topic):

    # A topic can be unread if a track for itself exists with a mark time that
    # is less important than its update date.
    topic_track = TopicReadTrack.objects.filter(topic=topic, user=user)

    topic_last_modification_date = topic.last_post_on or topic.created

    if topic_track.exists() and topic_last_modification_date > topic_track.values_list('mark_time', flat=True)[0]:
        return True

    # A topic can be unread if a track for its associated forum exists with
    # a mark time that is less important than its creation or update date.
    forum = topic.forum
    forum_track = ForumReadTrack.objects.filter(forum=forum, user=user)
    #tracked_forums = dict(forum_tracks.values_list('forum__pk', 'mark_time'))

    if forum_track.exists() and not topic_track and topic_last_modification_date > forum_track.values_list('mark_time', flat=True)[0]:
        return True

    # A topic can be unread if no tracks exists for it
    if not forum_track.exists() and not topic_track.exists():
        return True

    return False
```

**Comment by vinniefalco** [comment]
What's the thinking for not providing the feature?

**Comment by sdarwin** [comment]
@savelmtr  Thank you very much for this email notification script!  It does seem to work quite well.

A point of discussion though, is the time.sleep(3600).

At first glance, perhaps this bundles together multiple notifications into a single message. 
However, that's not exactly what happens. 
It simply delays each and every email for an hour. And thus, potentially avoids the transmission of an email altogether if the user has read the topic within an hour.  
The main problem with that method is if the web server gets restarted during the hour (which could happen, considering such a long time period), the notification will be completely lost. 
A secondary question could be "what would github do here? what would another forum implementation do here?"  
Github sends notifications approximately "immediately". And, regardless of other factors. 
So, perhaps it would be better to comment out the sleep statement.

Another small feedback: you might go further in documenting the complete set of changes that you made, and to which files, even to the extent of submitting a pull request...     If I have time, will try to do that.

**Comment by sdarwin** [comment]
> these precautions help us avoid too frequency mailing.  

That does makes sense.

Every forum is different.  The ideal case would be to allow a configurable delay, from 0 seconds to 3600 seconds, or any value.   

But also, avoid missing any notifications. Maybe you achieve that by "just put this info in json field in his profile."

If your newer solution works very well for you, maybe find a way to share it here, somehow.  :-)    

In any case, we will also need to implement this in the forum.

**Comment by pnizet** [comment]
@savelmtr @ellmetha I'm interested by the functionality also,
Thanks @savelmtr for you proposition, but it seems that you have modify some other parts of the code as I get this error : 
`AttributeError: 'ForumProfile' object has no attribute 'allow_mail_if_participant'`
Can you share the other parts ??
Thanks
