### ISSUE TITLE
Posts with polls crash when viewed as anonymous user

### ISSUE THREAD

**Issue by thomastu** [ellmetha/django-machina#2]
To reproduce, I gave the anonymous user read permissions for "see forum", "read forum", etc.

```
Exception Type: 	AttributeError
Exception Value: 	'AnonymousUser' object has no attribute 'poll_votes'
```

Relevant template :  machina/templates/machina/forum_conversation/forum_polls/poll_detail.html
```
{% get_permission 'can_vote_in_poll' poll request.user as user_can_vote_in_poll %}
```

Relevant Code : machina/apps/forum_permission/handler.py line 181
```
user_votes = user.poll_votes.filter(poll_option__poll=poll)
```

If you provide an expected behaviour, I think I can provide a fix.

**Comment by ellmetha** [comment]
Hi,
Thanks for reporting this. I can reproduce this error. Anonymous users are not properly managed as part of this permission check. The ``can_vote_in_poll`` method of the ``PermssionHandler`` should be updated. The ``has_been_completed_by`` template filter also need to be updated to properly handle this case.

Can you provide a fix (with the relevant unit tests) ?
