### ISSUE TITLE
Problem with redirections

### ISSUE THREAD

**Issue by william27wp** [ellmetha/django-machina#201]
Hi Everyone
I've installed Machina on the server :
https://scenarmag.fr/myapp/forum/

I've created a post for test :
https://scenarmag.fr/myapp/forum/forum/dramatica-1/topic/je-ne-parviens-plus-à-me-connecter-à-wwwscenarmagfr-1/

so far so good

But from this page, the urls changed. I've lost /myapp/
How can i fix this? if possible.

Thanks for your help
William

**Comment by hazho** [comment]
you have to check the views.py + url.py of the certain app in the machina module..!
if you couldn't find the way to solve it, pm me directly.. or provide more details, so we can help you further.
