### ISSUE TITLE
Error when trying to run python manage.py migrate

### ISSUE THREAD

**Issue by pidigodi** [ellmetha/django-machina#202]
Hi,
 I'm getting this error (ImportError: cannot import name 'six' from 'django.utils**') when I run migrate.
Thanks!

**Comment by william27wp** [comment]
I solved this error by replacing all the [Django-machina](https://github.com/ellmetha/django-machina/tree/master/machina) and [Haystack ](https://github.com/django-haystack/django-haystack/tree/master/haystack)files in virtualenv with those available on github.

**Comment by savelmtr** [comment]
@pidigodi , I've dropped out the haystack dependency in #187, so you could install Django-machina from my repo or you could wait until this PR will pe accepted. In that case you'll be free of installing  Haystack.

**Comment by SeYoungKim** [comment]
I had the same problem with Django 3.

For now, I just downgraded Django to 2

then "python manage.py migrate" worked.

**Comment by elitwilliams** [comment]
+1 for this issue, six dependency in haystack breaks the installation for me (python 3.7.7, Django 3.0.7)

**Comment by ellmetha** [comment]
This can be solved by simply installing Django-Haystack's latest pre-release (`3.0b2`). 😉 
Closing this issue!
