### ISSUE TITLE
When we move topic, the attributes 'last_post' of the old forum and new forum are not change

### ISSUE THREAD

**Issue by savelmtr** [ellmetha/django-machina#208]
This problem is quite simple, I think we should fix it. For this purpose i propose to add some code renewing info about last_post to the `save()` method of `AbstractForum`. What do you think about this, @ellmetha? I'm ready to make such a PR.

**Comment by ellmetha** [comment]
Fixed in https://github.com/ellmetha/django-machina/commit/32417b1b1d4fad5f7c9ec92748f15c11b6ac1457. Thanks for reporting this!
