### ISSUE TITLE
500 error on demo site

### ISSUE THREAD

**Issue by gusreyes01** [ellmetha/django-machina#211]
While trying to review the demo site I received a 500 error multiple times which prevented me from continuing testing:

<img width="1070" alt="Captura de Pantalla 2020-08-28 a la(s) 9 13 49" src="https://user-images.githubusercontent.com/2120129/91577852-f35d1880-e90e-11ea-862c-8da96d085895.png">

**Comment by ellmetha** [comment]
This is fixed. Thanks!
