### ISSUE TITLE
Some feature proposals

### ISSUE THREAD

**Issue by H-M-H** [ellmetha/django-machina#23]
Are there any plans to add:
- a function to report posts to admins/moderators
- a banning system possibly combined with warnings users can get from moderators, so they are automatically banned for some time if they got their third warning for example
- private messages, so you can talk to specific users privately
- softdelete posts so admins/moderators can still have a look at them later

Some background info: I am searching for forumsoftware I can nicely integrate with the django-project I am building at the moment. The current forum is based on phpBB and thus not exactly what I want :P. So after some search I came across django-machina and had a closer look at it. And the above list is what I feel is somewhat missing.

If you consider any of those things as doable I can add an issue for each request separately.

I hope it is ok to bolt in like this :)

**Comment by ellmetha** [comment]
Hi!

Thanks for your message. ;) My answers below:

**Feature (1)**

> a function to report posts to admins/moderators

:+1:  This is a feature that is definitely associated with forum applications. So I agree with this proposal ; this should be implemented.

**Feature (2)**

> a banning system possibly combined with warnings users can get from moderators, so they are automatically banned for some time if they got their third warning for example

Well this is perhaps too specific to some applications. The central aim of *django-machina* is to provide a generic module that can be easily integrated into existing Django projects. This it does not make any assumptions about how a user should be considered as banned. Some projects could have a very specific policy regarding how to ban their users (this could be related to forum features... or not) and I don't want *django-machina* to interfere with that.

**Feature (3)**

> private messages, so you can talk to specific users privately

This is not directly related to forum applications. Often you will find standalone forum applications providing private messages (such as phpbb indeed). However a private messaging system is not a feature that is specific to forum applications. In the scope of a Django project you would use another third-party application to implement such a messaging system (you can see https://djangopackages.org/grids/g/messaging/ for a list of applications handling private messages between users).

**Feature (4)**

> softdelete posts so admins/moderators can still have a look at them later

:+1:  I agree, this could be necessary in some cases. So I could plan to implement it.

Can you add an issue for the features **(1)** and **(4)** separately ? :)

**Comment by H-M-H** [comment]
Thanks for your answer !

Nice that you also consider some of my proposals as useful :)
I will add issues for them separately.

Another proposal that came to my mind are notifications if someone mentioned you in a post.

**Comment by ellmetha** [comment]
Hi ! ;)

Sorry for the late answer.

> Another proposal that came to my mind are notifications if someone mentioned you in a post.

It could be interesting. I'll think about it. In the meantime can you create another issue for this feature?

**Comment by H-M-H** [comment]
> Sorry for the late answer.

Don't worry, I am patient :)

So, you got another issue from me now :P
