### ISSUE TITLE
Disable attachment

### ISSUE THREAD

**Issue by jimma1** [ellmetha/django-machina#230]
Hello and thanks for the forum.

I am using it for the first time now, and I want to disable the attachment options. 

So far I have overwritten templates in `forum_conversation` so we can show the `Options` tab, but not the `Attachments` tab. For instance in the file `post_form.html` you must have `attachment_formset` to render the option tab. Further the `machina.attachment.init()` is also removed in templates and the setting `MACHINA_ATTACHMENT_MAX_FILES_PER_POST` is sat to 0.

Templates overwritten:

- post_forum.html
- topic_forum.html
- post_create.html
- post_update.html
- topic_create.html
- topic_update.html

Another way to remove the attachment functionality seems to be setting the `attachment_formset` to None for views in `forum_conversation`, but this I have not tested.

**Question**
It seems to me that overwriting several templates to remove the attachment upload tab and keep the options tab is too tedious, so is there another way to do this which I have not found/understood? 

If not, I would suggest a setting to turn attachment upload on/off.

**Comment by ellmetha** [comment]
As an admin user you will always see the attachment tab but if you do not grant the [permissions](https://django-machina.readthedocs.io/en/stable/forum_permissions.html) to upload attachments to your users, they will never see anything regarding attachments (nor have the ability to upload them). 😉

**Comment by jimma1** [comment]
@ellmetha HA! Excellent. Thanks for the answer :) No need to add any other functionality around turning attachment on/off.
