### ISSUE TITLE
Search feature not working. 

### ISSUE THREAD

**Issue by snehlata08** [ellmetha/django-machina#245]
I have followed all the steps given in this [Tutorial](https://django-machina.readthedocs.io/en/stable/getting_started.html) but the search feature for my project is not working. Whereas the example project given by django-machina is working fine with search. So can someone tell me what is the missing thing. I have also rebuild and updated the index. But still  my search is not giving any results. It is always 0 results with no error. 
```
python3 manage.py rebuild_index

/usr/local/lib/python3.8/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
/usr/local/lib/python3.8/site-packages/haystack/backends/simple_backend.py:31 UserWarning: clear is not implemented in this backend
All documents removed.
Indexing 13 Posts
/usr/local/lib/python3.8/site-packages/haystack/backends/simple_backend.py:25 UserWarning: update is not implemented in this backend
```

**Comment by Pei2tech** [comment]
I use below setting and it work fine.  You can try it. 

```  
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Machina dependencies:
    'mptt',
    'haystack',
    'widget_tweaks',

    # Machina apps:
    'machina',
    'machina.apps.forum',
    'machina.apps.forum_conversation',
    'machina.apps.forum_conversation.forum_attachments',
    'machina.apps.forum_conversation.forum_polls',
    'machina.apps.forum_feeds',
    'machina.apps.forum_moderation',
    'machina.apps.forum_search',
    'machina.apps.forum_tracking',
    'machina.apps.forum_member',
    'machina.apps.forum_permission',

    ##### your app should be here after machina 
    App

]
```
I also suggest to install Whoosh engine and the setting as follows:

```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

```
Please don't forget to create a directory named "whoosh_index".   
hope this can help you.

**Comment by snehlata08** [comment]
@Pei2tech @ellmetha  thank you for the help. It has started working. But there is a problem. I have to manually run the `update_index` command to make the search work. And any new topic or posts created after that are not getting indexed on their own. For them as well I have run the update_index command again. Can you please help me with this What do i need to do to make it work on its own.

**Comment by Pei2tech** [comment]
@snehlata08  I use postgresql and don't have the issue you post.

**Comment by snehlata08** [comment]
i use postgresql as well. but i still face this problem.

**Comment by Pei2tech** [comment]
Did you configure the HAYSTACK_SIGNAL_PROCESSOR in the settings.py?  If you don't configure it, please configure it as below:
```
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
``` 
I have used the whoosh for my project. If you also use it, you should find whoosh_index directory in the root of project, and any new posts should also update the MAIN_xxxxxxxx.seq file.  You can add a new posts and check the date/time of file in the whoosh_index.
