### ISSUE TITLE
Сan't enable login through the django-machina interface

### ISSUE THREAD

**Issue by 0gk** [ellmetha/django-machina#250]
I suspect that due to a lack of experience (the first my project on Dzhangо and I am rather a system administrator than a programmer) I am stupid in some very simple moment.

Here on the demo forum https://demo.machina-forum.io/ there is an opportunity to register and logon in in the right corner of the top panel. And when I setup and run Django-machina, there are no such links in interface.

I read the documentation, especially carefully the section on permissions. I looked in Google, no one asks about it. But on YouTube there is a video in which a person shows how to install and configure this app, and he also does not have links to registration. And he does not pay attention to it at all.

I suspect that this is some kind of thing so obvious that it is not even mentioned anywhere. The authorization module in Django is enabled. Maybe something else needs to be included, and the forum will display these links?

Please tell me how you can enable registration directly through the forum?

And I'm sorry if this question is out of place here, I just don't know where to ask anymore.

**Comment by Pei2tech** [comment]
There is no register interface for the library, but you can refer to the [demo](https://github.com/ellmetha/machina-demo), which already included some code can handle the register interface and more.
