### ISSUE TITLE
How to extend models of django-machina in other modules?

### ISSUE THREAD

**Issue by savelmtr** [ellmetha/django-machina#253]
Hello everyone!
I tried to use my code implementing postgres-search to standalone module. This code perfectly worked when it was a part of my version of django-machina. But when I moved it in standalone module I got `LookupError: App 'machina_search' doesn't have a 'Post' model.` Actually I has no idea why could I got such an info, cause the model `Post` in file "models.py" was created & the module machina_search was added into settings. What have I missed?

**Comment by mslinn** [comment]
Did you commit your work in a new branch, so others can see the problem?

**Comment by savelmtr** [comment]
> Did you commit your work in a new branch, so others can see the problem?

Yeah, here it is: https://github.com/savelmtr/django-machina-search

**Comment by savelmtr** [comment]
I thought that proxy-models would work, but new fields in such type of models don't supported by Django.

**Comment by savelmtr** [comment]
Ok, raw sql is my friend.
