### ISSUE TITLE
Extending this to a site similar to SMF?

### ISSUE THREAD

**Issue by Jzarecta** [ellmetha/django-machina#26]
I would like to replace SMF with this forum, but one of the issues I found is that it lacks certtain social features like direct messages, and more extended user fields, I wonder if there are some code/plugin that can provide that extendability.

**Comment by ellmetha** [comment]
Hi ;-)

The aim of *django-machina* is to provide a solid core of a forum project that can be easily integrated into existing Django projects. Thus *django-machina* don't provide functionalities such as direct messages. It's true that often you will find standalone forum software (such as SMF) providing DM functionalities. However *django-machina* is not a standalone forum application. This kind of features is not directly related to forum applications and can be used by a wide range of applications. This is why *django-machina* does not provide direct messages or private messages : you can add a messaging system to your Django application without relying on *django-machina* (you can see https://djangopackages.org/grids/g/messaging/ for a list of applications handling private messages between users).

**Comment by Jzarecta** [comment]
I see, that is too bad I was hoping on replacing SMF with a competent solution. And is true, is not part of the core functionality of Forum, but that's what have made a lot of people explain from a full Forum application. 
Another functionality that I was hoping to find and maybe it can be label as part of the full core functionality is the Web Notification API for events such as post replies, polling, etc.

**Comment by ellmetha** [comment]
Hi ;)

> I see, that is too bad I was hoping on replacing SMF with a competent solution. And is true, is not part of the core functionality of Forum, but that's what have made a lot of people explain from a full Forum application.

I agree but as I said you'll find plenty of Django applications handling private messages between users. It should really not be that difficult to combine these applicattions with *django-machina*. :-)

> Another functionality that I was hoping to find and maybe it can be label as part of the full core functionality is the Web Notification API for events such as post replies, polling, etc.

I don't plan to include this kind of functionalities into *django-machina* right now. In the meantime you could use another application specialized in such notifications or implement it by yourself.

I'll close this issue now. Feel free to open other issues if you have other suggestions. :-)
