### ISSUE TITLE
 forum_moved = django.dispatch.Signal(providing_args=["previous_parent", ])

### ISSUE THREAD

**Issue by frame318** [ellmetha/django-machina#267]
I have installed according to the manual when makemigrations get the following error 

forum_moved = django.dispatch.Signal(providing_args=["previous_parent", ])
TypeError: __init__() got an unexpected keyword argument 'providing_args'

**Comment by frame318** [comment]
Now I was able to solve the initial problem by downgrading the django version to 3.2 from 4.0.     

I will wait for further updates and fixes. Thanks.

**Comment by azzeloof** [comment]
I ran into the same problem! Unfortunate downgrading isn't an option for me, so I'll have to keep an eye out for updates too.

**Comment by BoPeng** [comment]
Same here.

**Comment by ellmetha** [comment]
Support for Django 4.0 was added in the `1.2.0` release. We can close this issue now. 🙂
