### ISSUE TITLE
List category by default

### ISSUE THREAD

**Issue by Jzarecta** [ellmetha/django-machina#28]
Hi I want to default the forum index to a category listing instead of the forum listing. Something similar to what NodeBB has. Here is a demo:
http://forum.rise.vision/
This will list the category using the CSS Grid and the fontawesome as the image thumbnail per category. 
Is this possible to list the categories first and then move to the rest of the list of topics once inside the category?
http://forum.rise.vision/category/1/announcements

**Comment by ellmetha** [comment]
To do this you'll have to override the template that is responsible for rendering forum lists. I don't have time to look more into this as it not really an issue (so I'll close this topic). Good luck!
