### ISSUE TITLE
Make posts or categories public to non users

### ISSUE THREAD

**Issue by Jzarecta** [ellmetha/django-machina#29]
I notice that the posts are not public and can only be viewed once regsitered as a user. Since I am manging a public project, I wonder if this is a variable that I can just switch on, or is this on the admin UI somehow.

**Comment by ellmetha** [comment]
Hi ;)

It depends on your forum permissions. By default forums cannot be seen by anonymous users. Please head over to the "Forum permissions" section of the documentation (https://django-machina.readthedocs.io/en/stable/forum_permissions.html).

**Comment by Jzarecta** [comment]
Well the default forum permission is **yes** for 'can_see_forum' however on the templates from the vanilla app it looks like it doesnt display, here is my test site:
http://oooes.org:8000/
However the global_forum permission is all green on the admin control:
http://picpaste.com/thumbs/Screenshot_20160809_113341-4aLCvZjH.1470760506.png

**Comment by ellmetha** [comment]
Your screen-shot does not works. ;) I cannot really help you if you does not provide additional information:

* your forum tree
* the global permissions and the permissions of the considered forums

**Comment by Jzarecta** [comment]
Sorry here:
http://i.imgur.com/OeDEj7u.png 
http://i.imgur.com/Ud1fDCh.png

**Comment by Jzarecta** [comment]
Were you able to see the screenshots?

**Comment by ellmetha** [comment]
Yes. So the permissions that I can see in the first screenshot... these are the permissions for anonymous users?
