### ISSUE TITLE
"forum/index.html" template improvement

### ISSUE THREAD

**Issue by devsf** [ellmetha/django-machina#30]
Hi,
some days ago, i started integrating the django-machina app into my company's application. I had some troubles with the customization of the template but after a brief look at the Vanilla Demo, everything is ok.
I would suggest a little improvement for the "machina/forum/index.html" template that should help users in css customization. The improvement allows "forumlist-top-controls", forum list and page-header/statistics elements to be better aligned and to group the page-header and statistics elements.
This is the improvement:
- before:
```
<h4 class="page-header">{% trans "Statistics" %}</h4>
<p class="statistics">{% trans "Total posts:" %}&nbsp;<b>{{ total_posts_count }}</b>&nbsp;&#8226;&nbsp;{% trans "Total topics:" %}&nbsp;<b>{{ total_topics_count }}</b>&nbsp;</p>
```
- after:
```
<div class="row">
    <div class="forum-page-statistics col-xs-12">
        <h4 class="page-header">{% trans "Statistics" %}</h4>
        <p class="statistics">{% trans "Total posts:" %}&nbsp;<b>{{ total_posts_count }}</b>&nbsp;&#8226;&nbsp;{% trans "Total topics:" %}&nbsp;<b>{{ total_topics_count }}</b>&nbsp;</p>
    </div>
</div>
```
I hope this could be useful.
Bye

**Comment by ellmetha** [comment]
Hi! Thanks for your message. Could you provide a Pull Request for these changes?

**Comment by devsf** [comment]
Hi! Yes, Pull Request #31 is ready!
This is my first pull request... So, tell me if something is wrong!
Thanks, bye!
