### ISSUE TITLE
module 'PIL.Image' has no attribute 'ANTIALIAS' with dependency pillow >= 10.0.0

### ISSUE THREAD

**Issue by barsch** [ellmetha/django-machina#308]
```Image.ANTIALIAS``` has been removed in Pillow 10.0.0 and needs to replaced with ```Image.LANCZOS``` or ```Image.Resampling.LANCZOS```

see https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants

It is currently used here:
https://github.com/ellmetha/django-machina/blob/6586d2608bbffc31911ea6f9a15c570580116238/machina/models/fields.py#L266

**Comment by Alsaheem** [comment]
For now , the following works
**_Uninstall pillow 10.0.1_**
pip uninstall Pillow

_**Install Pillow 9.5.0**_
pip install Pillow==9.5.0

**Comment by bioworkflows** [comment]
@ellmetha Could you please merge https://github.com/ellmetha/django-machina/pull/311 and create a new minor release of django-machina?

**Comment by BoPeng** [comment]
@ellmetha Could you please merge https://github.com/ellmetha/django-machina/pull/311 and create a new minor release of django-machina?

**Comment by ellmetha** [comment]
The new 1.3.1 minor release is available. Thanks for the PR @BoPeng!
