### ISSUE TITLE
Markdown not parsing on Topic Detail page

### ISSUE THREAD

**Issue by y2kbadbug** [ellmetha/django-machina#35]
I am using pagedown and in the preview it parses the markdown just fine, however in the topic detail it does not parse the markdown at all.

Version: 0.3.0

Machina Settings:
# Machina settings
MACHINA_MARKUP_LANGUAGE = None
MACHINA_MARKUP_WIDGET = 'pagedown.widgets.PagedownWidget'
MACHINA_FORUM_NAME = 'IRC Driven'
MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS = [
    'can_see_forum',
    'can_read_forum',
    'can_start_new_topics',
    'can_reply_to_topics',
    'can_edit_own_posts',
    'can_post_without_approval',
    'can_create_polls',
    'can_vote_in_polls',
    'can_download_file',
]

**Comment by ellmetha** [comment]
You have to set the ``MACHINA_MARKUP_LANGUAGE`` setting in order to store the HTML resulting of the Markdown transformation when you create a post. ;-) See: https://django-machina.readthedocs.io/en/stable/settings.html#machina-markup-language

**Comment by y2kbadbug** [comment]
You are the man!  Fixed my issue, thanks!
