### ISSUE TITLE
Editing posts of others overwrites poster field

### ISSUE THREAD

**Issue by strindhaug** [ellmetha/django-machina#39]
It seems that if the user has permission to edit posts of others and they use the frontend-form to do the edits; the `poster` field will be overwritten with the user doing the edit. So that it appears like the admin originally wrote the post, and the original author is unable to edit their own post (since it's no longer theirs), and it will disappear from "My posts" list etc...

(This can't possibly be intended behavior, can it?)

**Comment by ellmetha** [comment]
No, this is not the intended behaviour. :wink:

**Comment by strindhaug** [comment]
At first, I thought maybe I was confusing myself when alt-tabbing between different browsers to test multiple users locally, and then maybe it was intentional, because why would the "owner-field" be overwritten accidentally in an edit form. 

But when I found the bug, and saw that it was in a ModelForm that handles both edit and creation it made more sense that it was an accident.

Btw, the line in the release note:

    Fixed a bug that allowed users to overwrite poster fields when editing a post submitted by another user (#39)

technically should be something like:

    Fixed a bug that caused the poster fields to be overwritten with the current user when editing a post submitted by another user (#39)

...because it wasn't an option that was revealed, the field was just automatically overwritten on every edit. (Not that it's very important)
