### ISSUE TITLE
Django 2.0 set to require on_delete for related fields

### ISSUE THREAD

**Issue by msaysell** [ellmetha/django-machina#45]
If you try to run the server using the `-Wd` flag, you become plagued with lots of warnings for machina stating that on_delete is set to be required.

     python -Wd manage.py runserver

For example,

>lib\site-packages\machina\apps\forum\abstract_models.py:33: RemovedInDjango20Warning: on_delete will be a required arg for TreeForeignKey in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior. See https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey.on_delete
  'self', null=True, blank=True, related_name='children', verbose_name=_('Parent'))

I've made a simple regex that you should be able to go through and find and replace all (or at least most) foreign keys that don't currently contain an on_delete to contain this so theres not much effort involved in fixing.

    (ForeignKey|OneToOneField)\(((?:(?!on_delete|ForeignKey|OneToOneField)[^\)])*)\)

replace with

    $1($2, on_delete=models.CASCADE)

See [my stackoverflow question](http://stackoverflow.com/questions/41571281/easy-way-to-set-on-delete-across-entire-application) for more info on what this regex does if required (or ask me! :) ).

Many thanks!

**Comment by ellmetha** [comment]
Thanks for pointing that out| :wink: Fixed in dd526b7.
