### ISSUE TITLE
conflict with jQuery

### ISSUE THREAD

**Issue by retosteffen** [ellmetha/django-machina#46]
Hi,
I have implemented django-machina in my app and so am loading jQuery before the django-machina's javascript and when I load both my jQuery and the js/machina.packages.min.js the moderation dropdown button doesn't work. Taking out either js scripts resolves the problem. Which packages (apart from jQuery) are included in the js/machina.packages.min.js file?

Thanks!

**Comment by ellmetha** [comment]
You can see how the JS files are built in the gulpfile: https://github.com/ellmetha/django-machina/blob/master/gulpfile.js#L29 :wink: Bootstrap is also included in the js/machina.packages.min.js file.

**Comment by retosteffen** [comment]
Ok. Then I'll just remove the js/machina.packages.min.js file from the board_base template.
Thanks
