### ISSUE TITLE
Bug with slugs

### ISSUE THREAD

**Issue by Sibiryakanton** [ellmetha/django-machina#48]
All details here:
http://stackoverflow.com/questions/42002784/noreversematch-in-django-machina-if-forums-title-contains-unicode-characters/42003197?noredirect=1#comment71310851_42003197

If name of forum in Russian language, appeared NoReverseMatch

**Comment by ellmetha** [comment]
Thanks for reporting this! This should be fixed in 0da60ab. :wink:

I shall release a new version of *django-machina* (including this fix) in a few days.
