### ISSUE TITLE
Edited post

### ISSUE THREAD

**Issue by nordbit** [ellmetha/django-machina#5]
```
<machina.models.fields.MarkupText object at 0x7f9be925db70>
````
In edit form, not formated Post
django==1.9.1 py-==3.5.1

off topic  - keep your good work, project look very promising, so far probably best forum engine in django world, well designed, easy to integrate with any django project.
Wishlist - upload (and display)  picture in editor or pluggable editor, not only Markup editor

**Comment by ellmetha** [comment]
Hi,
Thanks for reporting this. Nice catch. ;)

**Comment by nordbit** [comment]
And in admin panel in forum description, and in display "{{ node.description.rendered }}" in forum_list.html (same bug I suppose)

**Comment by ellmetha** [comment]
This bug should not appear anymore with the fix I pushed yesterday. Could you please create another issue if you encounter this problem again?
