### ISSUE TITLE
TemplateSyntaxError Django 1.9.x

### ISSUE THREAD

**Issue by kkomninos** [ellmetha/django-machina#52]
The requirements in docs mention Django 1.8+ but in 1.9 I'm getting a **TemplateSyntaxError:**  **Unused 'is' at end of if expression.** when I'm trying to see a forum. According to Django docs "is" in template added in 1.10.
 In topic_list.html  there is the if clause: **{% if not force_all_unread and unread_topics is None %}**
where I changed the **is** to **==** in order to work.

**Comment by ellmetha** [comment]
Hi! Thanks for reporting this. The patch in bb58423 will be part of the upcoming `0.5.2` release. :wink:
