### ISSUE TITLE
Pagination calculations for posts incorrect

### ISSUE THREAD

**Issue by norman-tan** [ellmetha/django-machina#53]
In the forum thread listing (and when posting), using the link  `/topic/topic-slug/?post=postid#postid` will result in the page number miscalculating when the page is full (i.e. posts in thread = n x TOPIC_POSTS_NUMBER_PER_PAGE).

For example, if posts in the thread = 30 (including the topic) and the `TOPIC_POSTS_NUMBER_PER_PAGE =15`, it will attempt to redirect to page 3 while page 2 is the intended behaviour.

The fix for the template tags is as follows;

`https://github.com/ellmetha/django-machina/blob/master/machina/templatetags/forum_conversation_tags.py`

    pages_number = ( (topic.posts_count-1) // machina_settings.TOPIC_POSTS_NUMBER_PER_PAGE) + 1

The fix for posts pagination in:

`https://github.com/ellmetha/django-machina/blob/master/machina/apps/forum_conversation/views.py`
 
requested_page = ((post.position-1) // machina_settings.TOPIC_POSTS_NUMBER_PER_PAGE) + 1

**Comment by ellmetha** [comment]
Fixed in 91af5e5. Thanks!
