### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by r-ku** [ellmetha/django-machina#6]
Any possibility to gain google/facebook/etc account logins? Something like [django-allauth](http://django-allauth.readthedocs.org/) provides.

**Comment by ellmetha** [comment]
Hi,

*Django-machina* is a generic module whose aim is to be easily integrated into existing Django projects. Thus it does not make any assumptions on how authentication is done in the projects where it is used. In fact *django-machina* doesn't handle authentication at all. :)

That said the example projects and the demo sites provide simple authentication mechanisms. It could be possible to use *django-allauth* in the demo project. But this is not really related to the forum engine provided by *django-machina*. ;)

**Comment by r-ku** [comment]
Oh i see, good to know django-machina is so flexible. Sorry for wasting your time ;)

**Comment by ellmetha** [comment]
It's OK. It doesn't hurt to ask! :)
