### ISSUE TITLE
Unable to extend Post object

### ISSUE THREAD

**Issue by yakky** [ellmetha/django-machina#7]
By following documentation I get ``RuntimeError: Conflicting 'post' models in application 'forum_conversation': <class 'machina.core.db.models.Post'> and <class 'apps.forum_conversation.models.Post'>.`` error
``Topic`` model from the same application works

**Comment by yakky** [comment]
I managed to solve this, documentation is misleading in this regard. This is how I fixed:

1. I defined in custom ``apps.forum_conversation.registry_config`` the custom ``AppConfig``:

        class ConversationRegistryConfig(BaseConversationRegistryConfig):
             name = 'apps.forum_conversation'

1. In ``apps.forum_conversation.__init__`` I set:

        default_app_config = 'apps.forum_conversation.registry_config.ConversationRegistryConfig'

    thus pointing to the local AppConfig

1. In ``apps.forum_conversation.models`` I changed the import to 

        from machina.apps.forum_conversation.models import Topic

    And defined the post as:

        class Post(AbstractPost):

            class Meta(AbstractPost.Meta):
                abstract = False
                app_label = 'forum_conversation'

I can provide a pull request for the documentation changes

**Comment by ellmetha** [comment]
Hi!

You're right. This documentation section is missing an explanation : the ``AppConfig`` of the original application should be overridden in order to specify the name of the new application. That said I am not sure if the redefinition of the model's ``Meta`` class is really necessary.

Could you try using the master branch (and the following commit : 34c15e7) ?

**Comment by yakky** [comment]
@ellmetha thanks for the quick review.
With the changes of your commit, Meta is not required and the import of the original models can be set to ``from machina.apps.forum_conversation.models import *  # noqa`` as stated in the documentation

**Comment by ellmetha** [comment]
Ok. That's cool! I guess that the steps related to the redefinition of the ``AppConfig``'s name should be added to the documentation.
Could you provide a pull request for these documentation changes? :)

**Comment by yakky** [comment]
@ellmetha definitely!

**Comment by yakky** [comment]
@ellmetha it took a while I managed to write the PR :)
