### ISSUE TITLE
Allowing only members of a group to see a forum

### ISSUE THREAD

**Issue by franga2000** [ellmetha/django-machina#78]
Hi, I have a question about how to do something with the permission system:
I want all forums to be accessible to everyone, except for one, which should be accessible only to the members of a specific group.

The way you do this in most forum software _(and what I tried to do)_ is:
- _Globally allow everyone access to all forums (I did this with a "Users" group, which everyone is in)_
- Add a negative (`Permission.has_perm =  False`) access permission for the forum to everyone
- Add a positive (`Permission.has_perm =  True`) access permission to the specific group

Because the positive comes after the negative, most forum software will give the members the permission. In machina however, this makes the forum inaccessible to everyone.

This is caused by the fact that the default permission checker doesn't respect the order of permissions. Specifically, [this line](https://github.com/ellmetha/django-machina/blob/master/machina/apps/forum_permission/checker.py#L90-L92), which filters out all permissions that have a corresponding negative one. While this is more predictable, it is also a lot less flexible.

My question is the following: 
Is this a bug and a PR fixing it would be accepted, or is this an intentional feature and I'm missing some very obvious way of achieving this?

**Comment by ellmetha** [comment]
Alright. I didn't see anything wrong in the way permissions are computed in the `PermissionChecker` class (if you look again you'll see that granted permissions win precedence over non granted permissions). That said I made a fix in the `PermissionHandler` class which fixes what you're trying to achieve (here: bbcd17d). 😉
