### ISSUE TITLE
BBCode Integration

### ISSUE THREAD

**Issue by nikkelj** [ellmetha/django-machina#80]
Hi,

I've got users begging for a bbcode integration too.  I've noticed the docs mention it, but some detail is eluding me, I am wondering if anyone can provide some deeper advice on how to perform, and maybe a good option for a BBCode integration if you've tried any?  (I will be digging on it but figured I should reach out and ask too.)

Thanks!

**Comment by nikkelj** [comment]
By the way, I very much like where this thing is going in general, you've made a lot of great architecture choices.

**Comment by franga2000** [comment]
I tried this a while back. I used [`django-precise-bbcode`](https://github.com/ellmetha/django-precise-bbcode) - it's from the same author as machina.
The package doesn't include an editor and I switched away from BBCode before I could find one, so the following is for a simple textarea without a WYSIWYG editor:

`util.py`: (name doesn't really matter)
```python
from precise_bbcode.bbcode import get_parser

def parse_bbcode(bbcode):
    parser = get_parser()
    html = parser.render(bbcode)
    return html
```

`settings.py`:
```python
MACHINA_MARKUP_WIDGET = "django.forms.widgets.Textarea"
MACHINA_MARKUP_LANGUAGE = ("util.parse_bbcode", {})
```

**Comment by nikkelj** [comment]
Thanks for the advice, that worked!
