### ISSUE TITLE
Mobile Viewport Issues

### ISSUE THREAD

**Issue by nikkelj** [ellmetha/django-machina#81]
One more for you today, and then I'll pipe down:

I've had some users complaining about a couple mobile viewport issues, I am mostly wondering if you think these are in the regime of things that might get fixed in the core, or if you see them as customization issues.  

- The mobile viewport appears to cut off the profile sidebar
- Embedded content like signatures, images, etc is allowed to grow past the edge of the post, and looks very awkward/unkempt.  It may be better to force the styling to either (possibly optionally) autosize imagery like that, or inner scroll it, more akin to how SMF works.

**Comment by ellmetha** [comment]
> The mobile viewport appears to cut off the profile sidebar

Yes. It is explicitly hidden for mobile devices. You'll have to customize the look and feel of the post layout if you want to change this!

> Embedded content like signatures, images, etc is allowed to grow past the edge of the post, and looks very awkward/unkempt. It may be better to force the styling to either (possibly optionally) autosize imagery like that, or inner scroll it, more akin to how SMF works.

Could you be more specific? This seems to be related to the editor chosen to generate the final HTML, right? If so, I don't think that this should be fixed in the core module. Otherwise I could look into it but you'll have to be more specific regarding how to reproduce the problem. 😉

**Comment by nikkelj** [comment]
Ok thanks, if that is an intentional design choice, I will customize it, that is understandable.

I am unsure, that is a good point, I'll try to understand if it is an artifact of the chosen editor (CKEditor at the moment), and get back to you.

**Comment by franga2000** [comment]
> Embedded content like signatures, images, etc is allowed to grow past the edge of the post

If you're talking about images inside the posts growing past the edge, I fixed that with the following:
```css
.post-content *, .post-signature * {
	max-width: 100%;
	overflow-x: auto; /* Not required, but might help in some cases (editor inline styles) */
}
```

**Comment by nikkelj** [comment]
Thanks, I'll give that a shot

**Comment by nikkelj** [comment]
This did the trick, thanks, closing issue
