### ISSUE TITLE
Browser Back Marks All Unread Topics As Read

### ISSUE THREAD

**Issue by nikkelj** [ellmetha/django-machina#83]
Received a report from a few of my users that, when navigating to unread threads, and then using the back button, all remaining unread threads get marked read.  I was able to verify myself.

**Comment by ellmetha** [comment]
I wasn't able to reproduce the problem. Could you give more details?

**Comment by nikkelj** [comment]
It appears to only behave this way when there are two unread posts, can you see if you see it with only that many?

**Comment by ellmetha** [comment]
No. I don't see any problem. 😉

**Comment by nikkelj** [comment]
Hmm well ok then, it must be due to some mod I've made

**Comment by ellmetha** [comment]
Alright, I'll close this conversation then. In the meantime if you observe this problem again (and if you're sure it is not related with one of your modifications), then feel free to open a new issue again with as much details as possible on how to reproduce the problem from an empty forum (with two users for example).

**Comment by franga2000** [comment]
A user just reported the same thing to me and I've managed to reproduce it only three times on the live site (still haven't managed to do it in a controlled environment so I don't have any logs).

I haven't modified the source code in any relevant way in my [fork](https://github.com/ellmetha/django-machina/compare/master...franga2000:totifoto) and the only templates I've overridden are `board_base.html` and `forum_member/forum_profile_update.html` which shouldn't effect this.

Warning: 12MB gif files ahead:

![vokoscreen-2017-12-02_12-20-25](https://user-images.githubusercontent.com/3891092/33515083-87270384-d75e-11e7-9fd8-d5c64d2de1dc.gif)
![vokoscreen-2017-12-02_12-22-31](https://user-images.githubusercontent.com/3891092/33515094-c4001476-d75e-11e7-9fba-9c34cd6e350c.gif)
