### ISSUE TITLE
Reverse for 'user_posts' not found after upgrading to 1.10

### ISSUE THREAD

**Issue by kkomninos** [ellmetha/django-machina#84]
I had Django-machina running for some time and I decided to upgrade Django to 1.10 from 1.9,  Now I have some problems when I try to access any page of the forum, even the index.

Here is the traceback:

> Environment:
> 
> Request Method: GET
> Request URL: http://******/forum/
> 
> Django Version: 1.10.7
> Python Version: 2.7.9
> Installed Applications:
> ['django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.sites',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.sitemaps',
>  'grappelli',
>  'django.contrib.admin',
>  'haystack',
>  'social_django',
>  'cars',
>  'sanitizer',
>  'cacheops',
>  'djcelery',
>  'django.contrib.humanize',
>  'compressor',
>  'adv_cache_tag',
>  'watson',
>  'mptt',
>  'widget_tweaks',
>  'hijack',
>  'compat',
>  u'machina',
>  'car.apps.forum',
>  'car.apps.forum_conversation',
>  u'machina.apps.forum_conversation.forum_attachments',
>  u'machina.apps.forum_conversation.forum_polls',
>  u'machina.apps.forum_feeds',
>  u'machina.apps.forum_moderation',
>  u'machina.apps.forum_search',
>  u'machina.apps.forum_tracking',
>  u'machina.apps.forum_member',
>  u'machina.apps.forum_permission']
> Installed Middleware:
> ('django.middleware.common.CommonMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'machina.apps.forum_permission.middleware.ForumPermissionMiddleware')
> 
> 
> Template error:
> In template /usr/local/lib/python2.7/dist-packages/machina/templates/machina/forum/index.html, error at line 0
>    Reverse for 'user_posts' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'forum/member/profile/(?P<pk>\\d+)/posts/$']   1 : {% extends 'board_base.html' %}
>    2 : {% load i18n %}
>    3 : {% load mptt_tags %}
>    4 : {% load forum_tags %}
>    5 : 
>    6 : {% block sub_title %}{% trans "Index" %}{% endblock sub_title %}
>    7 : 
>    8 : {% block content %}
>    9 : 	<br />
>    10 : 	<div class="row">
> 
> 
> Traceback:
> 
> File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
>   42.             response = get_response(request)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
>   217.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
>   215.                 response = response.render()
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/response.py" in render
>   109.             self.content = self.rendered_content
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/response.py" in rendered_content
>   86.         content = template.render(context, self._request)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py" in render
>   66.             return self.template.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   208.                     return self._render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
>   174.         return compiled_parent._render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
>   174.         return compiled_parent._render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in _render
>   199.         return self.nodelist.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py" in render
>   70.                 result = block.nodelist.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
>   315.                 return nodelist.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render
>   994.                 bit = node.render_annotated(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/base.py" in render_annotated
>   961.             return self.render(context)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py" in render
>   439.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
> 
> File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py" in reverse
>   91.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
> 
> File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py" in _reverse_with_prefix
>   392.             (lookup_view_s, args, kwargs, len(patterns), patterns)
> 
> Exception Type: NoReverseMatch at /forum/
> Exception Value: Reverse for 'user_posts' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'forum/member/profile/(?P<pk>\\d+)/posts/$']

It might has to do with the middleware, if I remove the lines from the template that cause the error, the next exception I get is 'str object has no attribute 'is_anonymous"'.

Since the upgrade I have fixed such exceptions in my application, but it seems that Machina is compatible with 1.10 so before trying to change anything I think is it better to ask for any ideas. Thank you.

**Comment by kkomninos** [comment]
Finally it was an error in settings.py after upgrade.

**Comment by ZenDraL** [comment]
I'm getting this error too running on Python 2.7, Django 1.11. 

I followed the instructions from getting started using copy and paste and don't see any differences in the settings / imports.  

I get the same str object has no attribute 'is_anonymous' error when I comment out the lines.

Do you by chance remember what setting you had wrong @kkomninos ?
