### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by nkgilley** [ellmetha/django-machina#85]
I've tried testing the search feature with the simple and whoosh haystack backend but I never get any search results or any errors.  I'm following directions in the documentation, any help would be appreciated.

Thanks,
Nolan

**Comment by ellmetha** [comment]
You probably forgot to run the Haystack's `update_index` command on order to update your search index. 😉

**Comment by nkgilley** [comment]
That was it it!  Thanks @ellmetha - BTW, loving this project, thanks!

**Comment by danielmcquillen** [comment]
FYI, running `python manage.py update_index` when using simple_backend gives the error:

 `...lib/python3.6/site-packages/haystack/backends/simple_backend.py:41: UserWarning: update is not implemented in this backend `

**Comment by morocarlo** [comment]
same problem for me. Have you solved?
