### ISSUE TITLE
Invalid template name in 'extends' tag

### ISSUE THREAD

**Issue by Robinsondev** [ellmetha/django-machina#86]
Hi There, 

Thank you very much for this awesome package.
I am building a website on which I am using Mezzanine and Django machina. After installing mezzanine then django machina, I got this error: " Invalid template name in 'extends' tag: ''. Got this from the 'MACHINA_BASE_TEMPLATE_NAME' variable."

I think i am missing something. I am very new to this. Please help me.

Thanks

**Comment by ellmetha** [comment]
You probably forgot to add the `machina.core.context_processors.metadata` to your context processors settings. 😉

**Comment by Robinsondev** [comment]
Thanks! a lot for that.  Now I have another problem, which is not directly related to django-machina. I now have another problem:
#mezzanine
 url("^mez/", include("mezzanine.urls")),

    # Apps
    url(r'^forum/', include(board.urls)),
When one is commented, the other works, both don't want to work together
:)

Do you have an idea of what coould be happening? I get 404 error.

**Comment by ellmetha** [comment]
Not at all. Never tried to use machina with mezzanine. What about trying to define your machina URLs above the mezzanine ones?
