### ISSUE TITLE
index page open in IE and Iphone as file with error!

### ISSUE THREAD

**Issue by dzyk** [ellmetha/django-machina#88]
See [http://sevasauto.ru](http://sevasauto.ru) for example in Iphone

**Comment by ellmetha** [comment]
Can you provide more details? On which versions did you encounter this problem?

**Comment by dzyk** [comment]
Last version django machine.  All iPhone. Windows 7. How can i check any details for you?

**Comment by dzyk** [comment]
![sevasautoerror](https://user-images.githubusercontent.com/3785331/32089855-257578da-baf5-11e7-910d-05c2aa1bdf15.jpg)
