### ISSUE TITLE
If you uncheck a post as approved, the posts_count doesn't decrease

### ISSUE THREAD

**Issue by martinburchell** [ellmetha/django-machina#89]
In the admin interface, if you uncheck the approved box for a post and save it, the posts count for the user who created it doesn't decrease. If you check the box again and save it, the posts count increases. So the post count is then incorrect for that user.

I can see there are performance benefits to the current system and I am wondering if calculating the posts count on-the-fly would be less prone to this kind of error. In my own instance I ran into another problem with the posts count getting out of sync because I hadn't properly set up the RegistryConfig in my customised forum_member app. So I had to write a temporary management command to recalculate them.

**Comment by ellmetha** [comment]
Thanks for reporting this issue. It has been fixed in 2719fdb. FYI yes calculating posts count on-the-fly would introduce too much requests (posts count are not only displayed in forum profile pages, but also in topics themselves).
