### ISSUE TITLE
New topic ID appears in drop-down when creating post from admin interface

### ISSUE THREAD

**Issue by martinburchell** [ellmetha/django-machina#90]
If you create a new topic in the admin interface and then create a new post, the topic is shown in the drop-down list by its ID. Would it be better to show the topic subject?

I know that the topic subject will then be overwritten by the first post subject when the the post is saved.

**Comment by ellmetha** [comment]
Well this doesn't seem like a problematic behaviour IMO (why create topic & posts in the Django admin by the way?). That said I don't see any reason for not accepting a small PR addressing this. 😉
