### ISSUE TITLE
If you create a topic through the admin interface, the number of replies is -1

### ISSUE THREAD

**Issue by martinburchell** [ellmetha/django-machina#91]
I don't know if it is expected for users to create topics through the admin interface, but if you do, a first post doesn't get created and associated with the topic. This means that the number of replies to a topic (posts_count -1) is then displayed as -1.

**Comment by ellmetha** [comment]
Indeed it is not expected for users to create topics through the admin interface. I don't see any reasons to do so. The admin models associated with machina models are there for debug purposes only - except for Forum objects. Moreover, in that particular case it makes no sense to leave the topic "empty" (that is without at least one post associated with it - whose `approved` value is consistent with the topic one).

**Comment by martinburchell** [comment]
@ellmetha - thanks for the clarification - I'll pass this on to our client
