### ISSUE TITLE
Topic and post counts do not decrease when they are deleted

### ISSUE THREAD

**Issue by nkgilley** [ellmetha/django-machina#94]
The total topic and post counts do not update to reflect the true count after topics or posts are deleted.

**Comment by ellmetha** [comment]
Thank you for taking the time to create an issue. Could you provide some detailed steps to reproduce the problem? Which version are you talking about? Thanks!

**Comment by nkgilley** [comment]
After trying to reproduce this, I realized that it only happens when I delete topics from the admin interface.
