### ISSUE TITLE
Post admin loads all topics to populate topic foreign key select widget

### ISSUE THREAD

**Issue by nvankampenhout** [ellmetha/django-machina#98]
When opening a post in django admin interface, the topic foreign key select widget is prepopulated with all topics. For a large number of topics, this causes a long load time or crash. On our production system, which has ~120K topics, it's not possible to edit a post in the django admin interface due to this issue. This can be fixed by adding topic to raw_id_fields in the PostAdmin model.

**Comment by ellmetha** [comment]
Fixed in #99.
